window.PROVE_CASES = [
  {
    id: "miranda", file: "miranda-v-arizona.html", name: "Miranda v. Arizona", year: "1966", topic: "POLICE QUESTIONING", amendments: "5TH + 6TH AMENDMENTS", image: "../assets/prove-your-case/miranda.svg", alt: "An interview room with two chairs, a table, and a speech bubble containing a question mark.",
    teaser: "A kidnapping and rape suspect confessed after two hours alone with police. That confession became the most important evidence at his trial.",
    question: "Can police use a confession if they never told the arrested person about the right to remain silent or the right to a lawyer?",
    story: ["In 1963, an 18-year-old woman in Phoenix reported that a man had kidnapped her, forced her into a car, and raped her. Police later arrested Ernesto Miranda after she identified him in a lineup.", "Two officers questioned Miranda alone in a police interview room for about two hours. He eventually confessed to the kidnapping and rape and signed a written statement.", "The statement said Miranda understood his legal rights. However, the officers admitted that they had not first explained his right to remain silent or his right to have a lawyer present during questioning.", "Prosecutors presented the confession to the jury. Miranda was convicted of kidnapping and rape and received a lengthy prison sentence."],
    notice: ["Miranda was in police custody. He was not free to leave.", "The questioning was meant to produce evidence.", "This case is about what police must explain before custodial interrogation—questioning a person who is under arrest."],
    constitution: [{label:"FIFTH AMENDMENT", text:"No person “shall be compelled in any criminal case to be a witness against himself.”", explain:"Compelled means forced. A person cannot be forced to provide testimony that helps prove their own guilt."}, {label:"SIXTH AMENDMENT", text:"An accused person has the right “to have the Assistance of Counsel for his defence.”", explain:"Counsel means a lawyer. A lawyer can explain rights and protect a person during a criminal case."}],
    sideA: {title:"THE CONFESSION SHOULD NOT BE USED", points:["A right is not meaningful if a person does not know it exists.", "Police questioning can create pressure, especially when a person is alone and under arrest.", "A clear warning protects the choice to speak or remain silent."]},
    sideB: {title:"THE CONFESSION SHOULD BE USED", points:["Miranda signed a paper saying the statement was voluntary.", "The Constitution protects against forced statements, but it does not list a required police script.", "Blocking a voluntary confession may keep useful evidence from a jury."]},
    prompts:["Which fact matters most?", "What did police need to do differently, if anything?", "Use one phrase from the Constitution in your reason."],
    ruling:{violated:true, vote:"5–4", holding:"The Court ruled that the confession could not be used because police had not first provided important warnings.", reason:"Before custodial interrogation, police must explain the right to remain silent, that statements may be used in court, and the right to a lawyer. These safeguards protect the Fifth Amendment choice not to incriminate oneself.", nuance:"The decision did not say every confession is forbidden. A person may choose to speak after knowingly and voluntarily giving up these rights.", source:"https://www.uscourts.gov/about-federal-courts/educational-resources/educational-activities/fifth-amendment-activities/miranda-v-arizona"}
  },
  {
    id:"riley", file:"riley-v-california.html", name:"Riley v. California", year:"2014", topic:"YOUR PHONE", amendments:"4TH AMENDMENT", image:"../assets/prove-your-case/riley.svg", alt:"A smartphone filled with message, photo, map, and calendar symbols beside a police badge.",
    teaser:"After a gang shooting, police found two loaded guns in David Riley's car. Then detectives opened his phone and discovered another connection to the crime.",
    question:"After arresting someone, should police need a warrant before searching that person's phone?",
    story:["In San Diego, several men fired multiple gunshots at a member of a rival gang as he drove past. The shooters escaped in an Oldsmobile connected to David Riley. Witnesses could not say for certain whether Riley had fired a gun.", "About three weeks later, police stopped Riley for expired registration tags and learned that his license was suspended. During the required inventory search before towing his car, officers found two loaded handguns. Ballistics testing later connected the guns to the earlier shooting.", "Police arrested Riley and took a smartphone from his pocket. Without a warrant, detectives searched its contacts, messages, photos, and videos. They found evidence of gang membership and a photograph of the Oldsmobile used after the shooting.", "Prosecutors used the phone evidence in a case involving attempted murder, shooting at an occupied vehicle, and assault with a semiautomatic firearm. Riley was convicted and sentenced to 15 years to life."],
    notice:["The phone itself was lawfully taken during the arrest.", "The dispute is about the phone's digital contents, not whether police could hold the device.", "A warrant is a judge's written permission to search, usually based on probable cause—a strong factual reason to believe evidence will be found."],
    constitution:[{label:"FOURTH AMENDMENT", text:"People have the right to be secure against “unreasonable searches and seizures.” Warrants must be supported by probable cause.", explain:"A search is a government examination of a place or information where privacy is reasonably expected. The amendment does not ban every search; it bans unreasonable ones."}],
    sideA:{title:"THE PHONE SEARCH VIOLATED PRIVACY", points:["A phone can hold years of private messages, photos, medical information, and location history.", "Searching all that data is much broader than checking a pocket for a weapon.", "Police could secure the phone and ask a judge for a warrant."]},
    sideB:{title:"THE PHONE SEARCH WAS REASONABLE", points:["Police found the phone on a person they had lawfully arrested.", "Evidence on a phone can be deleted or remotely erased.", "Officers have traditionally searched items carried by an arrested person without a separate warrant."]},
    prompts:["Is a phone more like a pocket or a personal archive? Why?", "What could police do while waiting for a warrant?", "Which search rule best balances safety, evidence, and privacy?"],
    ruling:{violated:true, vote:"9–0", holding:"The Court ruled that police generally must get a warrant before searching the digital contents of a phone seized during an arrest.", reason:"Modern phones hold an enormous amount of deeply personal information. Searching that data is far more revealing than searching an ordinary physical object in a pocket.", nuance:"Police may still secure the phone and may act without a warrant in a true emergency, called an exigent circumstance.", source:"https://www.govinfo.gov/app/details/USREPORTS-573/USREPORTS-573-373"}
  },
  {
    id:"mahanoy", file:"mahanoy-v-bl.html", name:"Mahanoy Area School District v. B.L.", year:"2021", topic:"SNAPCHAT + SCHOOL", amendments:"1ST AMENDMENT", image:"../assets/prove-your-case/mahanoy.svg", alt:"A phone showing a social media post beside a school megaphone and pom-pom.",
    teaser:"After missing varsity cheer, a student posted an angry Snapchat with raised middle fingers and explicit language. Screenshots quickly reached her coaches.",
    question:"Should a public school be allowed to punish a student for a social-media post made off campus on the weekend?",
    story:["A high-school student identified in court as B.L. tried out for varsity cheerleading and a preferred softball position. She did not get either one, although the school offered her a place on junior-varsity cheer.", "That Saturday, B.L. and a friend went to a local convenience store. Using her own phone, B.L. posted a Snapchat photo of both girls raising their middle fingers. The caption said, “Fuck school fuck softball fuck cheer fuck everything.” A second post complained that some students had to spend a year on junior varsity while others did not.", "The posts were visible for 24 hours to B.L.'s roughly 250 Snapchat friends. Another student took screenshots. The images spread among students, and several cheerleaders went to the coaches visibly upset.", "After speaking with the principal, the coaches suspended B.L. from cheerleading for one year because they believed the posts were disrespectful and broke team rules."],
    notice:["The post used offensive words, but it did not threaten anyone.", "It was created off campus, outside school hours, on a personal phone.", "The school argued that the post broke team rules and harmed team morale."],
    constitution:[{label:"FIRST AMENDMENT", text:"Government may not make a law “abridging the freedom of speech.”", explain:"Abridging means limiting. Public schools are government institutions, so their discipline can raise First Amendment questions. Student speech rights exist, but they are not unlimited."}],
    sideA:{title:"THE PUNISHMENT VIOLATED FREE SPEECH", points:["Students need strong protection when they speak away from school and outside school hours.", "The post expressed frustration and did not threaten anyone.", "If schools control off-campus speech, students may have no place where they can speak freely." ]},
    sideB:{title:"THE PUNISHMENT WAS ALLOWED", points:["B.L. chose to join a school team with rules about respect and conduct.", "The post targeted the cheer program and created conflict among team members.", "Schools need authority to protect activities from serious disruption." ]},
    prompts:["How much should location and timing matter?", "Does joining a team change a student's speech rights?", "What kind of off-campus speech should a school still be able to address?"],
    ruling:{violated:true, vote:"8–1", holding:"The Court ruled that this punishment violated B.L.'s First Amendment right to free speech.", reason:"Schools have less authority over off-campus speech. B.L. spoke outside school hours, did not use school equipment, and did not cause the kind of substantial disruption that justified the punishment.", nuance:"The Court did not say schools can never address off-campus speech. Serious bullying, threats, cheating, or disruption may give a school a stronger reason to act.", source:"https://www.supremecourt.gov/opinions/20pdf/20-255_g3bi.pdf"}
  },
  {
    id:"carpenter", file:"carpenter-v-united-states.html", name:"Carpenter v. United States", year:"2018", topic:"YOUR LOCATION", amendments:"4TH AMENDMENT", image:"../assets/prove-your-case/carpenter.svg", alt:"A city map with a trail of location dots connecting a smartphone to cell towers.",
    teaser:"A group robbed electronics stores at gunpoint. Investigators used 12,898 phone-location points to place Timothy Carpenter near several robberies.",
    question:"Should police need a warrant before collecting months of a person's phone-location records?",
    story:["Over about two years, a group committed armed robberies at RadioShack and T-Mobile stores in Michigan and Ohio. The robbers entered the stores with guns, forced employees and customers toward the back, and stole new smartphones.", "After police arrested several suspects, one confessed. He gave investigators Timothy Carpenter's name and phone number and said Carpenter helped organize the robberies and often acted as a lookout.", "Prosecutors used a federal court order—not a search warrant based on probable cause—to make Carpenter's wireless companies provide historical cell-site records.", "The companies produced 12,898 location points covering 127 days. Prosecutors used those records to place Carpenter's phone near four robbery locations, and a jury convicted him of several robbery and gun crimes."],
    notice:["Cell-site location information is created when a phone connects to nearby towers.", "Carpenter did not type or post these locations. His phone created them while connecting to the network.", "The government received the records from phone companies, not directly from Carpenter's phone."],
    constitution:[{label:"FOURTH AMENDMENT", text:"People have the right to be secure against “unreasonable searches and seizures.” Warrants must be supported by probable cause.", explain:"A reasonable expectation of privacy is privacy that society is prepared to recognize and protect. Courts use this idea when new technology is not named in the Constitution."}],
    sideA:{title:"COLLECTING THE RECORDS WAS A SEARCH", points:["Months of location points can reveal a detailed picture of a person's life.", "Carrying a phone is a normal part of modern life, not a real choice to surrender privacy.", "Police should show probable cause to a judge before collecting such a long record." ]},
    sideB:{title:"COLLECTING THE RECORDS WAS NOT A SEARCH", points:["The records belonged to the phone companies and were kept for business purposes.", "Carpenter's phone sent information to a third party—the wireless provider.", "Police used a court order authorized by a federal law, even though it required less than probable cause." ]},
    prompts:["Does it matter that a company held the records?", "How much location history becomes too much?", "Explain what privacy a person should expect while carrying a phone."],
    ruling:{violated:true, vote:"5–4", holding:"The Court ruled that obtaining at least seven days of historical cell-site location information is a Fourth Amendment search and generally requires a warrant.", reason:"A long location record gives the government a revealing view of a person's movements. People do not truly choose to share every location simply by using a phone.", nuance:"The decision was narrow. It did not decide every question involving real-time tracking, short periods of records, emergencies, or national security.", source:"https://www.supremecourt.gov/opinions/17pdf/16-402_new_o75q.pdf"}
  },
  {
    id:"earls", file:"board-v-earls.html", name:"Board of Education v. Earls", year:"2002", topic:"SCHOOL DRUG TESTS", amendments:"4TH AMENDMENT", image:"../assets/prove-your-case/earls.svg", alt:"Theater masks, a music note, and an athletic ball beside a sealed drug-test sample cup.",
    teaser:"An Oklahoma school required students in activities such as choir, band, academic team, and athletics to submit to random drug tests.",
    question:"Can a public school require students in competitive activities to take random drug tests when the school does not suspect them of using drugs?",
    story:["An Oklahoma public school district was concerned about illegal drug use among students. It adopted a rule requiring drug tests for every student who wanted to join a competitive extracurricular activity—not only students suspected of using drugs.", "The rule covered athletics but also activities such as choir, marching band, color guard, Future Farmers of America, and academic team. Students were tested before joining, randomly during the year, and when school officials had reasonable suspicion.", "Students provided a urine sample in a closed restroom stall while a staff member waited outside. The sample was tested for several illegal drugs. Results were kept in school records and were not given to police.", "Lindsay Earls participated in choir, show choir, marching band, and academic team. She and another student challenged the policy because the school had no individual reason to suspect them of drug use."],
    notice:["A positive result did not lead to police charges or ordinary school discipline. It limited participation in activities.", "The policy applied without individualized suspicion—a specific reason to suspect one student.", "Joining these activities was voluntary, but the activities were an important part of school life."],
    constitution:[{label:"FOURTH AMENDMENT", text:"People have the right to be secure against “unreasonable searches and seizures.”", explain:"A urine test is a search because it collects private information from a person's body. The legal question is whether this search was reasonable."}],
    sideA:{title:"THE TESTING VIOLATED PRIVACY", points:["The school had no specific reason to suspect Earls of drug use.", "Providing a urine sample is personal and can feel humiliating.", "Students should not have to trade a constitutional right for music, clubs, or academic activities." ]},
    sideB:{title:"THE TESTING WAS REASONABLE", points:["Schools are responsible for student safety and preventing drug use.", "Activity participants already follow added rules and have a somewhat reduced expectation of privacy.", "Results were kept confidential and caused activity consequences rather than criminal punishment." ]},
    prompts:["Does choosing an activity make the search more reasonable?", "How does the way results are used affect your ruling?", "Should suspicion be required before testing one student?"],
    ruling:{violated:false, vote:"5–4", holding:"The Court ruled that the policy was a reasonable search and did not violate the Fourth Amendment.", reason:"The school had a strong interest in preventing student drug use. The testing process was limited, results were confidential, and students in competitive activities had a reduced expectation of privacy.", nuance:"The dissent argued that testing students without evidence of a real drug problem or individual suspicion weakened an important protection against government searches.", source:"https://www.govinfo.gov/app/details/USREPORTS-536/USREPORTS-536-822"}
  },
  {
    id:"miller", file:"miller-v-alabama.html", name:"Miller v. Alabama", year:"2012", topic:"JUVENILE LIFE SENTENCE", amendments:"8TH AMENDMENT", image:"../assets/prove-your-case/miller.svg", alt:"A young person's silhouette facing a judge's gavel and a calendar with no marked release date.",
    teaser:"Fourteen-year-old Evan Miller robbed and beat a neighbor, then helped set fire to the man's trailer. The victim died inside.",
    question:"Should a judge be required to give a person under 18 life in prison without parole for murder without considering the person's age or circumstances?",
    story:["Fourteen-year-old Evan Miller and his friend Colby Smith went to neighbor Cole Cannon's trailer, where the three drank alcohol and used marijuana. After Cannon passed out, Miller stole his wallet and split about $300 with Smith.", "When Miller tried to return the wallet, Cannon woke up and grabbed him by the throat. Smith struck Cannon with a baseball bat. Miller then took the bat and repeatedly beat Cannon, placed a sheet over his head, said he had come to take Cannon's life, and struck him again.", "The boys left, then returned to destroy evidence by setting two fires inside the trailer. Cannon died from his injuries and smoke inhalation.", "Miller was tried as an adult and convicted of murder committed during arson. Alabama law automatically required life in prison without parole, so the judge could not consider Miller's age, background, or possibility of change before imposing that sentence."],
    notice:["The crime was extremely serious and a person died.", "This case challenged a mandatory sentence. Mandatory means the judge had no choice.", "Parole is supervised release after part of a sentence. Life without parole means no ordinary chance for release."],
    constitution:[{label:"EIGHTH AMENDMENT", text:"Government may not inflict “cruel and unusual punishments.”", explain:"The amendment limits punishments that are constitutionally excessive. Courts consider both the seriousness of the crime and the characteristics of the person being punished."}],
    sideA:{title:"THE REQUIRED SENTENCE WAS CRUEL AND UNUSUAL", points:["Young people are still developing and may have a greater ability to change.", "A judge should consider age, family conditions, pressure from others, and the person's role in the crime.", "A mandatory rule treats every juvenile case exactly like the worst possible case." ]},
    sideB:{title:"THE REQUIRED SENTENCE WAS ALLOWED", points:["Murder causes permanent harm, regardless of the offender's age.", "States need power to set serious punishments for serious crimes.", "A jury convicted Miller as an adult, and the sentence followed the law in effect." ]},
    prompts:["What differences between youth and adults matter at sentencing?", "Does your answer depend on the seriousness of the crime?", "Should a judge have a choice even if the final sentence could still be life without parole?"],
    ruling:{violated:true, vote:"5–4", holding:"The Court ruled that mandatory life without parole for crimes committed under age 18 violates the Eighth Amendment.", reason:"A sentencing judge must be able to consider youth and the individual circumstances before imposing the harshest prison sentence on a juvenile.", nuance:"The decision did not completely ban juvenile life without parole. It banned making that sentence automatic without an individualized hearing.", source:"https://www.govinfo.gov/app/details/USREPORTS-567/USREPORTS-567-460"}
  }
];
